In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 20 11:46:40 2018

@author: prithvi_29
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data=pd.read_excel('process.xls');
data=data.fillna(0);
X = data.iloc[:,1:].values #-1 means exclude last column
Y = data.iloc[:,0].values #taking values from last column 

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


/home/prithvi_29/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
rfe = RFE(classifier,192)
rfe.fit(X_train,y_train)
y_pred = rfe.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm
# print summaries for the selection of attributes
# print(rfe.support_)
# print(rfe.ranking_)

array([[ 2, 35],
       [ 1, 54]])

In [4]:
# Create your classifier here
from sklearn.feature_selection import RFE
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
rfe = RFE(classifier,192)
rfe.fit(X_train,y_train)
y_pred = rfe.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[35,  2],
       [ 1, 54]])

In [5]:
from sklearn.svm import SVC
from sklearn.feature_selection import RFE
#for Linear SVM set kernel='linear'
classifier = SVC(kernel='linear',random_state=0)
rfe = RFE(classifier,192)
rfe.fit(X_train,y_train)
y_pred = rfe.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[37,  0],
       [ 1, 54]])

In [6]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
rfe = RFE(classifier,192)
rfe.fit(X_train,y_train)
y_pred = rfe.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[37,  0],
       [ 0, 55]])

In [7]:
from collections import Counter
Counter(y_test)

Counter({' malware': 37, ' normal': 55})